"use client";
import {useEffect,useState} from "react";
import {Button} from "@/components/ui/button";
import "../store/store-admin.css";
type Order={id:string;order_no:string;status:string;fulfillment:string;delivery_stage:string;delivery_address:string;total:string;note:string;created_at:string;full_name:string;phone:string;items:{name:string;quantity:number}[]};
export default function OnlineOrders(){
 const [rows,setRows]=useState<Order[]>([]),[filter,setFilter]=useState("pending"),[error,setError]=useState(""),[canCancel,setCanCancel]=useState(false),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch("/api/online-orders",{cache:"no-store"});if(!r.ok)throw new Error("Bu bölmə üçün hesabınıza daxil olun.");const d=await r.json() as {rows:Order[];canCancel:boolean};setRows(d.rows);setCanCancel(d.canCancel);setError("")}catch(e){setError(e instanceof Error?e.message:"Yüklənmədi")}}
 useEffect(()=>{void load();const t=setInterval(()=>void load(),15000);return()=>clearInterval(t)},[]);
 async function update(id:string,status:string){setBusy(true);try{const r=await fetch("/api/online-orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);await load()}catch(e){setError(e instanceof Error?e.message:"Saxlanmadı")}finally{setBusy(false)}}
 return <main className="store-admin"><a href="/admin">← İdarə paneli / Giriş</a><span className="sa-eyebrow" style={{display:"block",marginTop:28}}>SİFARİŞ MƏRKƏZİ</span><h1>Onlayn sifarişlər</h1><p>Saytdan gələn sifarişləri hazırlayın. Ödəniş və təhvil kassada tamamlanır.</p><nav className="sa-tabs">{[["pending","Yeni"],["ready","Hazır"],["completed","Tamamlandı"],["cancelled","Ləğv edilib"]].map(([id,label])=><button key={id} className={filter===id?"selected":""} onClick={()=>setFilter(id)}>{label} · {rows.filter(r=>r.status===id).length}</button>)}<button onClick={load}>Yenilə</button></nav>{error&&<p role="alert" className="form-error">{error}</p>}<div style={{display:"grid",gap:16}}>{rows.filter(r=>r.status===filter).map(o=><article className="panel settings-form" key={o.id}><div className="sa-title"><div><small>{new Date(o.created_at).toLocaleString("az-AZ",{timeZone:"Asia/Baku"})}</small><h2>{o.full_name}</h2><p>{o.phone} · {o.fulfillment==="delivery"?"Çatdırılma":"Mağazadan götürmə"}</p><p>{o.delivery_address}</p><p>{({received:"Qəbul edildi",preparing:"Hazırlanır",ready:"Hazırdır",dispatched:"Yoldadır",delivered:"Çatdırıldı"} as Record<string,string>)[o.delivery_stage]}</p></div><strong>{Number(o.total).toFixed(2)} ₼</strong></div><small style={{overflowWrap:"anywhere"}}>{o.order_no}</small><div style={{margin:"20px 0"}}>{o.items?.map((i,n)=><p key={n} style={{padding:"8px 0",borderBottom:"1px solid #eee"}}>{i.name} <strong>× {i.quantity}</strong></p>)}</div>{o.note&&<p>{o.note}</p>}<div style={{display:"flex",gap:10,marginTop:16}}>{o.status!=="cancelled"&&o.status!=="completed"&&<>{o.delivery_stage==="received"&&<Button disabled={busy} onClick={()=>update(o.id,"preparing")}>Hazırlamağa başla</Button>}{o.delivery_stage==="preparing"&&<Button disabled={busy} onClick={()=>update(o.id,"ready")}>Hazırdır</Button>}{o.delivery_stage==="ready"&&o.fulfillment==="delivery"&&<Button disabled={busy} onClick={()=>update(o.id,"dispatched")}>Yola sal</Button>}{o.delivery_stage==="dispatched"&&<Button disabled={busy} onClick={()=>update(o.id,"delivered")}>Çatdırıldı</Button>}</>}{canCancel&&["pending","ready"].includes(o.status)&&<Button disabled={busy} variant="outline" onClick={()=>update(o.id,"cancelled")}>Sifarişi ləğv et</Button>}</div></article>)}{!rows.some(r=>r.status===filter)&&<p className="empty-table">Bu bölmədə sifariş yoxdur.</p>}</div></main>
}
