import { NextResponse } from "next/server";
import { logSystemError } from "@/lib/log-error";
import { cookies } from "next/headers";
import { createHash,randomBytes,scrypt as scryptCallback,timingSafeEqual } from "node:crypto";
import { promisify } from "node:util";
import postgres from "postgres";

export const runtime="nodejs";
export const dynamic="force-dynamic";
const scrypt=promisify(scryptCallback),cookieName="birkassa_session";
const connection=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL təyin edilməyib");return postgres(process.env.DATABASE_URL,{max:1,prepare:false,connect_timeout:10})};
const permissions:Record<string,string[]>={admin:["*"],manager:["İdarə paneli","Satış / POS","Məhsullar","Anbar","Sifarişlər","Satınalma","Maliyyə","İnsan resursları","Hesabatlar","Nəzarət jurnalı"],cashier:["İdarə paneli","Satış / POS","Sifarişlər"],warehouse:["İdarə paneli","Məhsullar","Anbar","Satınalma"],accountant:["İdarə paneli","Maliyyə","Hesabatlar"]};
async function hashPin(pin:string,salt=randomBytes(16).toString("hex")){const derived=await scrypt(pin,salt,64) as Buffer;return`${salt}:${derived.toString("hex")}`}
async function verifyPin(pin:string,stored:string){const [salt,key]=stored.split(":");if(!salt||!key)return false;const derived=await scrypt(pin,salt,64) as Buffer,expected=Buffer.from(key,"hex");return derived.length===expected.length&&timingSafeEqual(derived,expected)}
const publicUser=(row:any)=>({id:row.id,fullName:row.full_name,role:row.role,permissions:permissions[row.role]||[]});

export async function GET(){const sql=connection();try{const store=await cookies(),token=store.get(cookieName)?.value;if(token){const hash=createHash("sha256").update(token).digest("hex");const [session]=await sql.unsafe("select u.id,u.full_name,u.role from auth_sessions s join users u on u.id=s.user_id where s.token_hash=$1 and s.expires_at>now() and u.is_active=true",[hash]);if(session)return NextResponse.json({authenticated:true,user:publicUser(session)})}const users=await sql.unsafe("select id,full_name,role,pin_hash is not null has_pin from users where is_active=true order by full_name");return NextResponse.json({authenticated:false,setupRequired:!users.some(u=>u.has_pin),users:users.map(u=>({id:u.id,fullName:u.full_name,role:u.role,hasPin:u.has_pin}))})}catch(error){console.error("auth.get",error);void logSystemError("auth.get", error);return NextResponse.json({error:"Giriş vəziyyəti yoxlanmadı"},{status:500})}finally{await sql.end({timeout:2})}}

export async function POST(request:Request){const sql=connection();try{const body=await request.json() as {action?:string;userId?:string;pin?:string;confirmPin?:string};const pin=String(body.pin||"");if(!/^\d{4,6}$/.test(pin))return NextResponse.json({error:"PIN 4–6 rəqəmdən ibarət olmalıdır"},{status:400});const user=await sql.begin(async tx=>{if(body.action==='setup'){const [{count}]=await tx.unsafe("select count(*)::int count from users where pin_hash is not null");if(Number(count)>0)throw Object.assign(new Error("İlk PIN artıq qurulub"),{statusCode:409});if(pin!==body.confirmPin)throw Object.assign(new Error("PIN təkrarı uyğun deyil"),{statusCode:400});const [admin]=await tx.unsafe("select id,full_name,role from users where is_active=true order by case when role='admin' then 0 else 1 end,created_at limit 1 for update");if(!admin)throw new Error("Administrator tapılmadı");await tx.unsafe("update users set pin_hash=$1,role='admin' where id=$2",[await hashPin(pin),admin.id]);return{...admin,role:'admin'}}if(!body.userId)throw Object.assign(new Error("İstifadəçini seçin"),{statusCode:400});const [found]=await tx.unsafe("select id,full_name,role,pin_hash from users where id=$1 and is_active=true",[body.userId]);if(!found||!found.pin_hash||!await verifyPin(pin,found.pin_hash))throw Object.assign(new Error("İstifadəçi və ya PIN düzgün deyil"),{statusCode:401});return found});const token=randomBytes(32).toString("base64url"),tokenHash=createHash("sha256").update(token).digest("hex"),expires=new Date(Date.now()+12*60*60*1000);await sql.unsafe("delete from auth_sessions where expires_at<=now()");await sql.unsafe("insert into auth_sessions (user_id,token_hash,expires_at) values ($1,$2,$3)",[user.id,tokenHash,expires]);const response=NextResponse.json({authenticated:true,user:publicUser(user)});response.cookies.set(cookieName,token,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",expires});return response}catch(error:any){console.error("auth.post",error);void logSystemError("auth.post", error);return NextResponse.json({error:error?.message||"Giriş tamamlanmadı"},{status:error?.statusCode||500})}finally{await sql.end({timeout:2})}}

export async function DELETE(){const sql=connection();try{const store=await cookies(),token=store.get(cookieName)?.value;if(token)await sql.unsafe("delete from auth_sessions where token_hash=$1",[createHash("sha256").update(token).digest("hex")]);const response=NextResponse.json({ok:true});response.cookies.set(cookieName,"",{httpOnly:true,path:"/",expires:new Date(0)});return response}finally{await sql.end({timeout:2})}}
