"use client";
import {FormEvent,useState} from "react";
import {AddressMap} from "./address-map";
export type AccountUser={id:string;name:string;email:string;phone:string;address:string;lat:number|null;lng:number|null};
type Place={label:string;lat:number;lng:number};
export function AccountSettings({user,onSaved}:{user:AccountUser;onSaved:()=>Promise<void>}){
 const [name,setName]=useState(user.name),[phone,setPhone]=useState(user.phone),[address,setAddress]=useState(user.address),[pin,setPin]=useState<{lat:number;lng:number}|null>(user.lat!=null&&user.lng!=null?{lat:user.lat,lng:user.lng}:null);
 const [query,setQuery]=useState(""),[places,setPlaces]=useState<Place[]>([]),[busy,setBusy]=useState(false),[note,setNote]=useState("");
 async function search(){setBusy(true);setNote("");try{const r=await fetch("/api/places?q="+encodeURIComponent(query));const d=await r.json() as {places?:Place[];error?:string};if(!r.ok)throw new Error(d.error);setPlaces(d.places||[]);if(!d.places?.length)setNote("Bu axtarışla ünvan tapılmadı.");}catch(err){setNote(err instanceof Error?err.message:"Axtarış alınmadı.");}finally{setBusy(false);}}
 async function choose(next:Pin){setPin(next);setBusy(true);try{const r=await fetch(`/api/places?lat=${next.lat}&lng=${next.lng}`);const d=await r.json() as {label?:string;error?:string};if(r.ok&&d.label)setAddress(d.label);}finally{setBusy(false);}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNote("");const form=new FormData(e.currentTarget);try{const r=await fetch("/api/customer-account",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,phone,address,lat:pin?.lat??null,lng:pin?.lng??null,currentPassword:String(form.get("currentPassword")||""),newPassword:String(form.get("newPassword")||"")||undefined})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setNote("Hesab ayarları saxlanıldı.");await onSaved();}catch(err){setNote(err instanceof Error?err.message:"Saxlanmadı.");}finally{setBusy(false);}}
 return <section className="account-settings"><div><span className="shop-tag">HESAB</span><h2>Hesab ayarları</h2><p>Ad, telefon və çatdırılma ünvanınızı yeniləyin. Ünvanı xəritədə nöqtə seçərək təyin edin.</p></div>
 <form className="ticket-form" onSubmit={save}><label>Ad və soyad<input value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={100}/></label><label>Telefon<input value={phone} onChange={e=>setPhone(e.target.value)} required pattern="[+0-9 ()-]{7,25}"/></label><label>E-poçt<input value={user.email} disabled/></label>
 <div className="address-picker"><div className="address-search"><label>Ünvan axtar<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Küçə, məhəllə və ya nişan"/></label><button type="button" className="shop-cart-button" disabled={busy||query.trim().length<3} onClick={()=>void search()}>Axtar</button></div>{!!places.length&&<ul className="address-results">{places.map(p=><li key={p.lat+","+p.lng}><button type="button" onClick={()=>{setAddress(p.label);setPin({lat:p.lat,lng:p.lng});setPlaces([]);}}>{p.label}</button></li>)}</ul>}<AddressMap pin={pin} onPick={next=>void choose(next)}/><label>Seçilmiş ünvan<textarea value={address} onChange={e=>setAddress(e.target.value)} maxLength={300} placeholder="Xəritədən seçin və ya ünvanı yazın"/></label>{pin&&<small>Xəritə nöqtəsi: {pin.lat}, {pin.lng}</small>}</div>
 <div className="address-search"><label>Cari şifrə<input name="currentPassword" type="password" autoComplete="current-password" placeholder="Şifrəni dəyişmək üçün"/></label><label>Yeni şifrə<input name="newPassword" type="password" minLength={8} maxLength={128} autoComplete="new-password" placeholder="Boş saxlasanız dəyişməz"/></label></div>
 <button className="shop-primary" disabled={busy}>{busy?"Saxlanılır…":"Ayarları saxla"}</button>{note&&<p role="status">{note}</p>}</form></section>;
}
type Pin={lat:number;lng:number};
