"use client";
import {useEffect,useState,FormEvent} from "react";
import {ShoppingBag,Search,Plus,Minus,Store,Package,X,Check} from "lucide-react";
import "./storefront.css";
type Product={id:string;name:string;category:string;unit:string;price:number;image:string;available:boolean};
type Brand={name:string;kind:string;description:string;logo:string;phone:string;address:string};
export default function Catalog(){
 const [account,setAccount]=useState<{name:string;phone:string}|null>(null),[fulfillment,setFulfillment]=useState("pickup"),[brand,setBrand]=useState<Brand|null>(null),[products,setProducts]=useState<Product[]>([]),[query,setQuery]=useState(""),[category,setCategory]=useState("Hamısı"),[cart,setCart]=useState<Record<string,number>>({}),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[receipt,setReceipt]=useState(""),[requestKey,setRequestKey]=useState("");
 async function load(){try{const r=await fetch("/api/catalog");const d=await r.json() as {brand:Brand;products:Product[];error?:string};if(!r.ok)throw new Error(d.error);setBrand(d.brand);setProducts(d.products);setCart(c=>Object.fromEntries(Object.entries(c).filter(([id])=>d.products.some(p=>p.id===id))));setError("")}catch{setError("Kataloq yüklənmədi. Yenidən yoxlayın.")}}
 useEffect(()=>{void fetch("/api/customer-account").then(r=>r.json()).then(d=>setAccount((d as {user:{name:string;phone:string}|null}).user));void load();const saved=sessionStorage.getItem("customer-cart");if(saved)try{setCart(JSON.parse(saved))}catch{};const timer=setInterval(()=>void load(),30000);setRequestKey(crypto.randomUUID());return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(products.length)sessionStorage.setItem("customer-cart",JSON.stringify(cart))},[cart,products.length]);
 const categories=["Hamısı",...new Set(products.map(p=>p.category||"Digər"))],visible=products.filter(p=>(category==="Hamısı"||(p.category||"Digər")===category)&&p.name.toLocaleLowerCase("az").includes(query.toLocaleLowerCase("az")));
 const lines=products.filter(p=>cart[p.id]>0),count=Object.values(cart).reduce((a,b)=>a+b,0),total=lines.reduce((s,p)=>s+p.price*cart[p.id],0);
 function change(id:string,delta:number){if(busy)return;setCart(c=>({...c,[id]:Math.min(100,Math.max(0,(c[id]||0)+delta))}))}
 async function order(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);try{const r=await fetch("/api/customer-orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestKey,fulfillment,address:f.get("address")||"",name:f.get("name"),phone:f.get("phone"),note:f.get("note")||"",items:lines.map(p=>({id:p.id,quantity:cart[p.id]}))})});const d=await r.json() as {order_no:string;error?:string};if(!r.ok)throw new Error(d.error);setReceipt(d.order_no);setCart({});setRequestKey(crypto.randomUUID())}catch(e){setError(e instanceof Error?e.message:"Sifariş göndərilmədi")}finally{setBusy(false)}}
 return <div className="shop"><div className="shop-announcement">Yaxınınızdakı seçimlər. Rahat sifariş. <span>Ödəniş təhvil zamanı</span></div><header className="shop-header"><a className="shop-brand" href="/">{brand?.logo?<img src={brand.logo} alt="Loqo"/>:<Store/>}<strong>{brand?.name||"Kataloq"}</strong></a><nav><a href="#catalog">Kataloq</a><a href="#contact">Əlaqə</a><a href="/account">Hesabım</a></nav><button className="shop-cart-button" onClick={()=>{setOpen(true);setReceipt("")}}><ShoppingBag size={18}/> Səbətim <b>{count}</b></button></header>
 <main><section className="shop-hero"><div><span className="shop-tag">{brand?.kind==="restaurant"?"MENYU • SİFARİŞ":"YERLİ MAĞAZA • ONLAYN KATALOQ"}</span><h1>{brand?.kind==="restaurant"?"Sevdiyiniz dadlar, hər gün sizinlə.":"Gününüzə lazım olan hər şey burada."}</h1><p>{brand?.description||"Məhsulları kəşf edin, seçiminizi edin və sifarişinizi bizə göndərin."}</p><a className="shop-primary" href="#catalog">Kataloqu kəşf et ↗</a><div className="shop-promises"><span>✓ Aktual seçimlər</span><span>✓ Asan sifariş</span></div></div><div className="shop-hero-art"><div className="shop-art-circle"/>{products.find(p=>p.image)?<img src={products.find(p=>p.image)!.image} alt="Kataloqdan seçim"/>:<div className="shop-art-icons"><ShoppingBag size={100}/><span>Hər gün yaxşı seçim.</span></div>}<div className="shop-float"><span>SEÇ, SİFARİŞ ET, GÖTÜR</span><strong>{brand?.name||"Sizin mağazanız"}</strong></div></div></section>
 <section id="catalog" className="shop-catalog"><div className="shop-section-title"><div><span>SİZİN ÜÇÜN SEÇDİK</span><h2>{brand?.kind==="restaurant"?"Menyumuzu kəşf edin":"Kataloqumuz"}</h2></div><label className="shop-search"><Search size={18}/><input aria-label="Məhsul axtar" placeholder="Nə axtarırsınız?" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="shop-categories">{categories.map(c=><button key={c} className={c===category?"selected":""} onClick={()=>setCategory(c)}>{c}</button>)}</div>{error&&!open&&<p role="alert">{error} <button onClick={load}>Yenidən yoxla</button></p>}<div className="shop-grid">{visible.map(p=><article className="shop-product" key={p.id}><div className="shop-image">{p.image?<img src={p.image} alt={p.name} loading="lazy"/>:<Package size={66}/>}<span>{p.category||"Digər"}</span></div><div className="shop-product-body"><small>{p.unit||"ədəd"} · {p.available?"Mövcuddur":"Hazırda bitib"}</small><h3>{p.name}</h3><div><strong>{p.price.toFixed(2)} <small>₼</small></strong><button className="shop-add" disabled={!p.available||busy} onClick={()=>cart[p.id]?setOpen(true):change(p.id,1)}>{cart[p.id]?"Səbətdə · "+cart[p.id]:"Səbətə əlavə et"}</button></div></div></article>)}</div>{brand&&!visible.length&&<p className="shop-empty">Bu seçimə uyğun məhsul tapılmadı.</p>}{!brand&&!error&&<p className="shop-empty">Kataloq yüklənir…</p>}</section>
 <section className="shop-contact" id="contact"><div><span>HƏR ZAMAN YAXININIZDA</span><h2>Bir sifariş qədər yaxınıq.</h2><p>{brand?.address||"Sifarişinizlə bağlı sizinlə əlaqə saxlayacağıq."}</p></div><strong>{brand?.phone||"Sifarişinizi kataloqdan göndərin"}</strong></section></main><footer><strong>{brand?.name||"Kataloq"}</strong><span>© {new Date().getFullYear()} · Rahat sifariş</span><a href="/account">Sifarişlərim</a></footer>
 {open&&<div className="shop-overlay"><section className="shop-drawer" role="dialog" aria-modal="true" aria-label="Sifarişiniz"><header><h2>Sifarişiniz</h2><button onClick={()=>!busy&&setOpen(false)} aria-label="Bağla"><X/></button></header>{receipt?<div className="shop-success"><Check size={48}/><h2>Sifarişiniz qəbul edildi!</h2><p>Komandamız sizinlə əlaqə saxlayacaq. Məhsullar təsdiqdən sonra hazırlanır.</p><small>{receipt}</small><a className="shop-primary" href="/account">Sifarişi izlə</a><button className="shop-primary" onClick={()=>setOpen(false)}>Kataloqa qayıt</button></div>:<><div className="shop-order-lines">{lines.map(p=><div key={p.id}><span>{p.name}<small>{(p.price*cart[p.id]).toFixed(2)} ₼</small></span><div className="shop-quantity"><button disabled={busy} onClick={()=>change(p.id,-1)}><Minus size={14}/></button>{cart[p.id]}<button disabled={busy} onClick={()=>change(p.id,1)}><Plus size={14}/></button></div></div>)}{!lines.length&&<p>İlk məhsulunuzu kataloqdan seçin.</p>}</div>{!account&&<p className="shop-note"><a className="shop-primary" href="/account">Daxil ol / Hesab yarat</a></p>}<form onSubmit={order}><div className="shop-total"><span>Cəmi</span><strong>{total.toFixed(2)} ₼</strong></div><label>Adınız<input name="name" defaultValue={account?.name||""} required minLength={2} maxLength={100}/></label><label>Telefon<input name="phone" defaultValue={account?.phone||""} type="tel" required placeholder="+994" maxLength={25}/></label><label>Təhvil üsulu<select value={fulfillment} onChange={e=>setFulfillment(e.target.value)}><option value="pickup">Mağazadan götürəcəyəm</option><option value="delivery">Ünvana çatdırılma</option></select></label>{fulfillment==="delivery"&&<label>Çatdırılma ünvanı<textarea name="address" required minLength={10} maxLength={500}/></label>}<label>Qeyd / masa nömrəsi<textarea name="note" maxLength={1000} placeholder="İstəyinizi burada qeyd edin"/></label><p className="shop-note">Onlayn ödəniş tutulmur. Sifariş və mövcudluq mağaza tərəfindən təsdiqlənəcək.</p>{error&&<p role="alert" className="shop-error">{error}</p>}<button className="shop-primary" disabled={busy||!lines.length||!account}>{busy?"Göndərilir…":"Sifarişi göndər"}</button></form></>}</section></div>}</div>
}
