"use client";
import {FormEvent,useEffect,useState} from "react";
type Line={id:string;sender:"customer"|"staff";body:string;edited_at:string|null;created_at:string};
type Ticket={id:string;ticket_no:string;subject:string;kind:"problem"|"suggestion"|"order";status:"open"|"answered"|"closed";created_at:string;updated_at:string;messages:Line[]};
const kindLabel={problem:"Problem",suggestion:"Təklif",order:"Sifariş"};
const statusLabel={open:"Gözləyir",answered:"Cavab var",closed:"Bağlı"};
function lastIsCustomer(ticket:Ticket){const last=ticket.messages.at(-1);return last?.sender==="customer";}
export function SupportDesk(){
 const [tickets,setTickets]=useState<Ticket[]>([]),[open,setOpen]=useState<string|null>(null),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[note,setNote]=useState(""),[editId,setEditId]=useState(""),[editSubject,setEditSubject]=useState("");
 async function load(){const r=await fetch("/api/account-chat");const d=await r.json() as {tickets?:Ticket[];error?:string};if(!r.ok)throw new Error(d.error);setTickets(d.tickets||[]);}
 useEffect(()=>{void load().catch(e=>setNote(e instanceof Error?e.message:"Biletlər yüklənmədi"));const t=setInterval(()=>void load().catch(()=>undefined),20000);return()=>clearInterval(t);},[]);
 async function send(body:unknown,form?:HTMLFormElement){setBusy(true);setNote("");try{const r=await fetch("/api/account-chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);form?.reset();setCreating(false);setEditId("");setEditSubject("");await load();}catch(e){setNote(e instanceof Error?e.message:"Saxlanmadı.");}finally{setBusy(false);}}
 const current=tickets.find(t=>t.id===open);
 return <section className="ticket-desk"><div className="ticket-head"><div><span className="shop-tag">DƏSTƏK</span><h2>Biletlərim</h2><p>Problem və təklif üçün bilet açın. Canlı söhbət WhatsApp-dadır, hər gün 08:00–19:00.</p></div><button className="shop-primary" type="button" onClick={()=>{setCreating(v=>!v);setOpen(null);}}>Yeni bilet</button></div>
 {creating&&<form className="ticket-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send({action:"create",subject:f.get("subject"),kind:f.get("kind"),message:f.get("message")},e.currentTarget);}}><label>Mövzu<input name="subject" required minLength={3} maxLength={120} placeholder="Qısa başlıq"/></label><label>Növ<select name="kind" defaultValue="problem"><option value="problem">Problem</option><option value="suggestion">Təklif</option><option value="order">Sifariş</option></select></label><label>Mesaj<textarea name="message" required minLength={10} maxLength={2000} placeholder="Nə baş verib və ya nə təklif edirsiniz?"/></label><button className="shop-primary" disabled={busy}>{busy?"Göndərilir…":"Bileti aç"}</button></form>}
 <div className="ticket-layout">{tickets.length?<ul className="ticket-list">{tickets.map(t=><li key={t.id}><button className={open===t.id?"selected":""} onClick={()=>{setOpen(t.id);setCreating(false);setEditId("");setEditSubject("");}}><b>#{t.ticket_no}</b><strong>{t.subject}</strong><small>{kindLabel[t.kind]} · {statusLabel[t.status]}</small></button></li>)}</ul>:<p className="account-empty">Hələ bilet yoxdur.</p>}
 {current&&<article className="ticket-view"><header><div><small>Bilet #{current.ticket_no}</small>{editSubject===current.id?<form onSubmit={e=>{e.preventDefault();void send({action:"subject",ticketId:current.id,subject:String(new FormData(e.currentTarget).get("subject")||"")});}}><input name="subject" required minLength={3} maxLength={120} defaultValue={current.subject}/><button disabled={busy}>Saxla</button><button type="button" onClick={()=>setEditSubject("")}>Ləğv</button></form>:<h3>{current.subject}</h3>}<span className={"ticket-status "+current.status}>{statusLabel[current.status]}</span></div>{current.status!=="closed"&&!current.messages.some(m=>m.sender==="staff")&&editSubject!==current.id&&<button type="button" onClick={()=>setEditSubject(current.id)}>Mövzunu düzəlt</button>}</header>
 <div className="ticket-thread">{current.messages.map(m=>{const editable=m.sender==="customer"&&current.messages.at(-1)?.id===m.id&&current.status!=="closed";return <div key={m.id} className={m.sender==="staff"?"ticket-note staff":"ticket-note"}>{editId===m.id?<form onSubmit={e=>{e.preventDefault();void send({action:"edit",messageId:m.id,message:String(new FormData(e.currentTarget).get("message")||"")});}}><textarea name="message" required minLength={2} maxLength={2000} defaultValue={m.body}/><button disabled={busy}>Saxla</button><button type="button" onClick={()=>setEditId("")}>Ləğv</button></form>:<><small>{m.sender==="staff"?"Mağaza":"Siz"} · {new Date(m.created_at).toLocaleString("az-AZ",{timeZone:"Asia/Baku"})}{m.edited_at?" · düzəldilib":""}</small><p>{m.body}</p>{editable&&<button type="button" onClick={()=>setEditId(m.id)}>Düzəlt</button>}</>}</div>;})}</div>
 {current.status!=="closed"&&<form className="ticket-form" onSubmit={e=>{e.preventDefault();void send({action:"reply",ticketId:current.id,message:String(new FormData(e.currentTarget).get("message")||"")},e.currentTarget);}}><label>Əlavə mesaj<textarea name="message" required minLength={2} maxLength={2000} placeholder={lastIsCustomer(current)?"Mağaza cavabını gözləyin və ya mesajı düzəldin":"Cavaba əlavəniz"}/></label><button className="shop-primary" disabled={busy}>Göndər</button></form>}
 {current.status==="closed"&&<p>Bu bilet bağlanıb. Yeni məsələ üçün yeni bilet açın.</p>}</article>}</div>{note&&<p role="status" className="shop-error">{note}</p>}</section>;
}
