import { NextResponse } from "next/server";
import { logSystemError } from "@/lib/log-error";
import postgres from "postgres";
import { findManagerByPin } from "@/lib/pin";

export const runtime="nodejs";
export const dynamic="force-dynamic";
const connection=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL təyin edilməyib");return postgres(process.env.DATABASE_URL,{max:1,prepare:false,connect_timeout:10})};

export async function GET(request:Request){const sql=connection();try{const userId=request.headers.get("x-birkassa-user-id");const customers=await sql.unsafe("select id,full_name,phone from customers order by created_at desc limit 100");const held=await sql.unsafe("select h.id,h.customer_id,h.items_json,h.discount,h.note,h.created_at,c.full_name customer_name from held_receipts h left join customers c on c.id=h.customer_id where h.cashier_id=$1 order by h.created_at desc",[userId]);const rules=await sql.unsafe("select key,value from system_settings where key in ('require_manager_void','max_discount_percent')");const map=Object.fromEntries(rules.map(row=>[row.key,row.value]));return NextResponse.json({requireManagerVoid:map.require_manager_void!=="false",maxDiscountPercent:Number(map.max_discount_percent??10),customers:customers.map(c=>({id:c.id,fullName:c.full_name,phone:c.phone||''})),held:held.map(h=>({id:h.id,customerId:h.customer_id,customerName:h.customer_name,items:typeof h.items_json==='string'?JSON.parse(h.items_json):h.items_json,discount:Number(h.discount),note:h.note,createdAt:h.created_at}))})}catch(error){console.error("pos-options.get",error);void logSystemError("pos-options.get", error);return NextResponse.json({error:"POS seçimləri yüklənmədi"},{status:500})}finally{await sql.end({timeout:2})}}

export async function POST(request:Request){const sql=connection();try{const userId=request.headers.get("x-birkassa-user-id");if(!userId)return NextResponse.json({error:"İstifadəçi sessiyası tapılmadı"},{status:401});const body=await request.json() as {action?:string;heldId?:string;managerPin?:string;items?:{productId:string;quantity:number}[];discount?:number;customerId?:string;customerName?:string;phone?:string;note?:string};if(body.action==='verify_manager'){const manager=await findManagerByPin(sql,String(body.managerPin||""));if(!manager)return NextResponse.json({error:"Rəhbər PIN-i düzgün deyil"},{status:403});await sql.unsafe("insert into audit_logs (user_id,action,entity_type,after_json) values ($1,'sale.void_approved','sale',$2)",[manager.id,JSON.stringify({cashierId:userId})]);return NextResponse.json({ok:true})}if(body.action==='customer'){const name=String(body.customerName||'').trim();if(name.length<2)return NextResponse.json({error:"Müştəri adını yazın"},{status:400});const [row]=await sql.unsafe("insert into customers (full_name,phone) values ($1,$2) returning id,full_name,phone",[name,body.phone||null]);return NextResponse.json({id:row.id,fullName:row.full_name,phone:row.phone||''},{status:201})}if(body.action==='delete_held'){if(!body.heldId)return NextResponse.json({error:"Gözləyən çek seçilməyib"},{status:400});await sql.unsafe("delete from held_receipts where id=$1 and cashier_id=$2",[body.heldId,userId]);return NextResponse.json({ok:true})}if(!Array.isArray(body.items)||!body.items.length)return NextResponse.json({error:"Gözlədiləcək çek boşdur"},{status:400});const [row]=await sql.unsafe("insert into held_receipts (cashier_id,customer_id,items_json,discount,note) values ($1,$2,$3::jsonb,$4,$5) returning id,created_at",[userId,body.customerId||null,JSON.stringify(body.items),Number(body.discount)||0,body.note||null]);return NextResponse.json(row,{status:201})}catch(error){console.error("pos-options.post",error);void logSystemError("pos-options.post", error);return NextResponse.json({error:"POS əməliyyatı saxlanmadı"},{status:500})}finally{await sql.end({timeout:2})}}
