"use client";
import {useEffect,useState,FormEvent} from "react";
import "./commerce-admin.css";
import {TicketDesk} from "./ticket-desk";
type Product={id:string;name:string;sku:string;category:string;unit:string;sale_price:string;cost_price:string;discount_price:string|null;description:string;specifications:string;is_active:boolean;image_url:string;stock:string};
type Coupon={id:string;code:string;percent:number;minimum:string;max_discount:string|null;expires_at:string;usage_limit:number;used:number;is_active:boolean};
type Message={id:string;name:string;email:string;phone:string;message:string;is_read:boolean;created_at:string};
type Data={products:Product[];coupons:Coupon[];messages:Message[]};
export default function CommerceManager(){
 const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState("products"),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[product,setProduct]=useState<Partial<Product>|null>(null),[coupon,setCoupon]=useState<Partial<Coupon>|null>(null);
 async function load(){try{const r=await fetch("/api/store-admin/commerce");const d=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(d.error);setData(d);}catch(e){setStatus(e instanceof Error?e.message:"Yüklənmədi.");}}
 useEffect(()=>{void load();},[]);
 async function save(body:unknown){setBusy(true);setStatus("");try{const r=await fetch("/api/store-admin/commerce",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(d.error);await load();setStatus("Dəyişiklik saxlanıldı.");return true;}catch(e){setStatus(e instanceof Error?e.message:"Saxlanmadı.");return false;}finally{setBusy(false);}}
 async function saveProduct(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const ok=await save({...f,action:"product",id:product?.id,sale_price:Number(f.sale_price),cost_price:Number(f.cost_price),discount_price:f.discount_price?Number(f.discount_price):null,is_active:f.is_active==="on"});if(ok)setProduct(null);}
 async function saveCoupon(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));const maxDiscount=Number(f.max_discount);const ok=await save({...f,action:"coupon",id:coupon?.id,percent:Number(f.percent),minimum:Number(f.minimum),max_discount:f.max_discount&&maxDiscount>0?maxDiscount:null,usage_limit:Number(f.usage_limit),expires_at:new Date(String(f.expires_at)).toISOString(),is_active:f.is_active==="on"});if(ok)setCoupon(null);}
 async function upload(id:string,file?:File){if(!file)return;setBusy(true);try{const body=new FormData();body.set("file",file);body.set("productId",id);const r=await fetch("/api/store-admin/upload",{method:"POST",body});const d=await r.json() as Data & {error?:string};if(!r.ok)throw new Error(d.error);await load();setStatus("Şəkil yeniləndi.");}catch(e){setStatus(e instanceof Error?e.message:"Şəkil yüklənmədi.");}finally{setBusy(false);}}
 const editor=product ? <form className="cm-editor" key={product.id||"new"} onSubmit={saveProduct}><h3>{product.id?"Məhsulu redaktə et":"Yeni məhsul"}</h3><div className="cm-fields">{[["name","Məhsul adı"],["sku","SKU"],["category","Kateqoriya"],["unit","Ölçü vahidi"]].map(([key,label])=><label key={key}>{label}<input name={key} required={key!=="category"} maxLength={key==="name"?200:key==="unit"?30:100} defaultValue={String(product[key as keyof Product]||"")}/></label>)}<label>Satış qiyməti ₼<input name="sale_price" type="number" step=".01" min=".01" max="1000000" required defaultValue={product.sale_price}/></label><label>Maya dəyəri ₼<input name="cost_price" type="number" step=".01" min="0" max="1000000" required defaultValue={product.cost_price||"0"}/></label><label>Endirimli qiymət ₼<input name="discount_price" type="number" step=".01" min=".01" defaultValue={product.discount_price||""} placeholder="Endirimsizdirsə boş saxlayın"/></label></div><label>Açıqlama<textarea name="description" maxLength={5000} defaultValue={product.description}/></label><label>Xüsusiyyətlər — hər sətirdə bir xüsusiyyət<textarea name="specifications" maxLength={3000} defaultValue={product.specifications} placeholder={"Çəki: 500 q\nİstehsalçı: …"}/></label><label className="cm-check"><input type="checkbox" name="is_active" defaultChecked={product.is_active}/> Aktiv məhsul</label><button disabled={busy}>Saxla</button><button type="button" disabled={busy} onClick={()=>setProduct(null)}>Bağla</button></form> : null;
 return <section className="commerce-admin"><nav>{[["products","Məhsul idarəsi"],["coupons","Endirim kuponları"],["messages","Dəstək biletləri"]].map(([id,label])=><button key={id} className={id===tab?"active":""} onClick={()=>{setTab(id);setProduct(null);setCoupon(null);}}>{label}</button>)}<a href="/admin/online">Sifarişləri idarə et ↗</a></nav>{status&&<p role="status" className="cm-status">{status}</p>}{!data?<p>Məlumatlar yüklənir…</p>:<>
 {tab==="products"&&<><div className="cm-toolbar"><div><h2>Məhsullarınız</h2><p>Yeni məhsullar stok daxil ediləndən sonra saytda görünür. Silmə tarixçəni qoruyaraq deaktiv edir.</p></div><button onClick={()=>setProduct({is_active:true,unit:"ədəd"})}>Yeni məhsul</button></div><div className="cm-toolbar"><input aria-label="Məhsul axtar" placeholder="Ad, SKU və kateqoriya…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Aktivlik" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Bütün məhsullar</option><option value="active">Aktiv</option><option value="inactive">Deaktiv</option><option value="discount">Endirimli</option></select></div>
 {product&&!product.id&&editor}
 <div className="cm-products">{data.products.filter(p=>(filter==="all"||filter==="active"&&p.is_active||filter==="inactive"&&!p.is_active||filter==="discount"&&p.discount_price)&&[p.name,p.sku,p.category].join(" ").toLocaleLowerCase("az").includes(query.toLocaleLowerCase("az"))).map(p=><article key={p.id} className={product?.id===p.id?"cm-product-card is-editing":"cm-product-card"}><div className="cm-product-summary">{p.image_url?<img src={p.image_url} alt={p.name}/>:<div className="cm-no-image">Şəkil yoxdur</div>}<div><small>{p.category||"Kateqoriyasız"} · {p.sku}</small><h3>{p.name}</h3><p>{Number(p.discount_price||p.sale_price).toFixed(2)} ₼ {p.discount_price&&<del>{Number(p.sale_price).toFixed(2)} ₼</del>}</p><span>{!p.is_active?"Deaktiv":Number(p.stock)>0?"Saytda aktiv":"Stok yoxdur"} · {Number(p.stock)} {p.unit}</span><div className="cm-actions"><button disabled={busy} aria-expanded={product?.id===p.id} onClick={()=>setProduct(product?.id===p.id?null:p)}>{product?.id===p.id?"Redaktəni bağla":"Redaktə et"}</button><button disabled={busy} onClick={()=>void save({...p,category:p.category||"",action:"product",sale_price:Number(p.sale_price),cost_price:Number(p.cost_price),discount_price:p.discount_price?Number(p.discount_price):null,is_active:!p.is_active})}>{p.is_active?"Deaktiv et":"Aktiv et"}</button></div><label className="cm-upload">Şəkil yüklə<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>void upload(p.id,e.target.files?.[0])}/></label></div></div>{product?.id===p.id&&editor}</article>)}</div></>}
 {tab==="coupons"&&<><div className="cm-toolbar"><div><h2>Endirim kuponları</h2><p>Faiz endirimi məhsul endirimindən sonra hesablanır. Maksimum məbləğ yazılsa, faiz ondan artıq düşmür. İstifadə sayı qəbul edilən sifarişlərdir; ləğv zamanı geri qaytarılmır.</p></div><button onClick={()=>setCoupon({is_active:true,percent:10,usage_limit:100})}>Yeni kupon</button></div>{coupon&&<form className="cm-editor" key={coupon.id||"new"} onSubmit={saveCoupon}><div className="cm-fields"><label>Kupon kodu<input name="code" required pattern="[A-Za-z0-9_-]{3,30}" defaultValue={coupon.code} placeholder="BAHAR10"/></label><label>Endirim %<input name="percent" type="number" min="1" max="90" required defaultValue={coupon.percent}/></label><label>Minimum səbət ₼<input name="minimum" type="number" min="0" max="1000000" step=".01" required defaultValue={coupon.minimum||"0"}/></label><label>Maksimum endirim ₼<input name="max_discount" type="number" min="0.01" max="1000000" step=".01" defaultValue={coupon.max_discount||""} placeholder="Limitsizdirsə boş saxlayın"/></label><label>Son tarix<input name="expires_at" type="datetime-local" required defaultValue={coupon.expires_at?new Date(new Date(coupon.expires_at).getTime()-new Date(coupon.expires_at).getTimezoneOffset()*60000).toISOString().slice(0,16):""}/></label><label>İstifadə limiti<input name="usage_limit" type="number" min="1" max="1000000" required defaultValue={coupon.usage_limit}/></label></div><label className="cm-check"><input name="is_active" type="checkbox" defaultChecked={coupon.is_active}/> Aktiv kupon</label><button disabled={busy}>Saxla</button><button type="button" onClick={()=>setCoupon(null)}>Bağla</button></form>}<div className="cm-coupons">{data.coupons.map(c=><article key={c.id}><strong>{c.code}</strong><h3>{c.percent}% endirim{c.max_discount?`, ən çoxu ${Number(c.max_discount).toFixed(2)} ₼`:""}</h3><p>Minimum {Number(c.minimum).toFixed(2)} ₼ · {c.used}/{c.usage_limit} istifadə</p><p>{new Date(c.expires_at).toLocaleString("az-AZ")} · {!c.is_active?"Deaktiv":new Date(c.expires_at)<new Date()?"Vaxtı bitib":"Aktiv"}</p><button onClick={()=>setCoupon(c)}>Redaktə / deaktiv et</button></article>)}</div>{!data.coupons.length&&<p>Hələ kupon yaradılmayıb.</p>}</>}
 {tab==="messages"&&<TicketDesk/>}
 </>}</section>;
}
