import { NextResponse } from "next/server";
import { logSystemError } from "@/lib/log-error";
import postgres from "postgres";
import { salesWarehouseSql } from "@/lib/warehouse";

export const runtime="nodejs";
export const dynamic="force-dynamic";
const connection=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL təyin edilməyib");return postgres(process.env.DATABASE_URL,{max:1,prepare:false,connect_timeout:10})};

export async function GET(){
  const sql=connection();
  try{
    const rows=await sql.unsafe(`select po.id,po.order_no,po.status,po.expected_date,po.total,po.note,po.created_at,po.received_at,s.name as supplier_name,coalesce(json_agg(json_build_object('productId',poi.product_id,'name',p.name,'quantity',poi.quantity,'unitCost',poi.unit_cost,'lineTotal',poi.line_total) order by poi.id) filter(where poi.id is not null),'[]'::json) as items from purchase_orders po join suppliers s on s.id=po.supplier_id left join purchase_order_items poi on poi.purchase_order_id=po.id left join products p on p.id=poi.product_id group by po.id,s.name order by po.created_at desc`);
    return NextResponse.json(rows.map(r=>({
      ...r,
      total:Number(r.total),
      items:r.items.map((i:any)=>({...i,quantity:Number(i.quantity),unitCost:Number(i.unitCost),lineTotal:Number(i.lineTotal)})),
    })));
  }catch(error){
    console.error("purchase.get",error);void logSystemError("purchase.get", error);
    return NextResponse.json({error:"Satınalmalar yüklənmədi"},{status:500});
  }finally{await sql.end({timeout:2})}
}

export async function POST(request:Request){const sql=connection();try{const body=await request.json() as {action?:string;orderId?:string;supplierId?:string;productId?:string;quantity?:number|string;unitCost?:number|string;expectedDate?:string;note?:string;locationCode?:string};if(body.action==='receive'){if(!body.orderId)return NextResponse.json({error:"Sifarişi seçin"},{status:400});const orderId=body.orderId;const result=await sql.begin(async tx=>{const [user]=await tx.unsafe("select id from users where id=$1 and is_active=true",[request.headers.get("x-birkassa-user-id")]);if(!user)throw Object.assign(new Error("İstifadəçi sessiyası tapılmadı"),{statusCode:401});const [order]=await tx.unsafe("select id,order_no,status,created_by from purchase_orders where id=$1 for update",[orderId]);if(!order)throw Object.assign(new Error("Sifariş tapılmadı"),{statusCode:404});if(order.status==='received')throw Object.assign(new Error("Bu sifariş artıq qəbul edilib"),{statusCode:409});const [warehouse]=await tx.unsafe(salesWarehouseSql(String(user.id)));if(!warehouse)throw new Error("Əsas anbar tapılmadı");const code=String(body.locationCode||"QƏBUL").trim().toUpperCase();let [location]=await tx.unsafe("select id from warehouse_locations where warehouse_id=$1 and code=$2 limit 1",[warehouse.id,code]);if(!location)[location]=await tx.unsafe("insert into warehouse_locations (warehouse_id,code) values ($1,$2) returning id",[warehouse.id,code]);const items=await tx.unsafe("select product_id,quantity,unit_cost from purchase_order_items where purchase_order_id=$1",[order.id]);for(const item of items){await tx.unsafe("insert into stock_movements (product_id,warehouse_id,location_id,type,quantity,unit_cost,reference_type,reference_id,performed_by,note) values ($1,$2,$3,'receipt',$4,$5,'purchase_order',$6,$7,$8)",[item.product_id,warehouse.id,location.id,item.quantity,item.unit_cost,order.id,user.id,`${order.order_no} mal qəbulu`]);await tx.unsafe("update products set cost_price=$1 where id=$2",[item.unit_cost,item.product_id])}await tx.unsafe("update purchase_orders set status='received',received_at=now() where id=$1",[order.id]);await tx.unsafe("insert into audit_logs (user_id,action,entity_type,entity_id,after_json) values ($1,'purchase.received','purchase_order',$2,$3)",[user.id,order.id,JSON.stringify({locationCode:code,itemCount:items.length})]);return{orderId:order.id,status:'received'}});return NextResponse.json(result,{status:201})}
const quantity=Number(body.quantity),unitCost=Number(body.unitCost);if(!body.supplierId||!body.productId||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(unitCost)||unitCost<0)return NextResponse.json({error:"Təchizatçı, məhsul, say və qiyməti düzgün yazın"},{status:400});const result=await sql.begin(async tx=>{const [user]=await tx.unsafe("select id from users where id=$1 and is_active=true",[request.headers.get("x-birkassa-user-id")]);if(!user)throw Object.assign(new Error("İstifadəçi sessiyası tapılmadı"),{statusCode:401});const [{next_no:nextNo}]=await tx.unsafe("select coalesce(max((regexp_replace(order_no,'[^0-9]','','g'))::bigint),0)+1 as next_no from purchase_orders");const orderNo=`SA-${String(nextNo).padStart(4,'0')}`;const total=Number((quantity*unitCost).toFixed(2));const [order]=await tx.unsafe("insert into purchase_orders (order_no,supplier_id,status,expected_date,total,note,created_by) values ($1,$2,'ordered',$3,$4,$5,$6) returning id,order_no",[orderNo,body.supplierId,body.expectedDate||null,total,body.note||null,user.id]);await tx.unsafe("insert into purchase_order_items (purchase_order_id,product_id,quantity,unit_cost,line_total) values ($1,$2,$3,$4,$5)",[order.id,body.productId,quantity,unitCost,total]);await tx.unsafe("insert into audit_logs (user_id,action,entity_type,entity_id,after_json) values ($1,'purchase.created','purchase_order',$2,$3)",[user.id,order.id,JSON.stringify({orderNo,total})]);return{orderId:order.id,orderNo,total,status:'ordered'}});return NextResponse.json(result,{status:201})}catch(error:any){console.error("purchase.action",error);void logSystemError("purchase.action", error);return NextResponse.json({error:error?.message||"Satınalma əməliyyatı tamamlanmadı"},{status:error?.statusCode||500})}finally{await sql.end({timeout:2})}}
