import { NextResponse } from "next/server";
import { logSystemError } from "@/lib/log-error";
import postgres from "postgres";

export const runtime="nodejs";
export const dynamic="force-dynamic";
const connection=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL təyin edilməyib");return postgres(process.env.DATABASE_URL,{max:1,prepare:false,connect_timeout:10})};

export async function GET(request:Request){const sql=connection();try{const url=new URL(request.url),from=url.searchParams.get("from")||new Date(Date.now()-29*86400000).toISOString().slice(0,10),to=url.searchParams.get("to")||new Date().toISOString().slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to))return NextResponse.json({error:"Tarix aralığı düzgün deyil"},{status:400});
  const [summary]=await sql.unsafe(`select coalesce(sum(s.total) filter(where s.status='completed'),0) sales,count(*) filter(where s.status='completed') receipts,coalesce(sum(s.total-costs.cost_total) filter(where s.status='completed'),0) profit,count(*) filter(where s.status='returned') returned_count from sales s left join lateral(select coalesce(sum(si.cost_snapshot*si.quantity),0) as cost_total from sale_items si where si.sale_id=s.id) costs on true where (s.created_at at time zone 'Asia/Baku')::date between $1::date and $2::date`,[from,to]);
  const daily=await sql.unsafe(`with dates as(select generate_series($1::date,$2::date,interval '1 day')::date as report_date) select d.report_date,coalesce(sum(s.total) filter(where s.status='completed'),0) total,count(s.id) filter(where s.status='completed') receipts from dates d left join sales s on (s.created_at at time zone 'Asia/Baku')::date=d.report_date group by d.report_date order by d.report_date`,[from,to]);
  const products=await sql.unsafe(`select p.name,p.sku,coalesce(sum(si.quantity),0) quantity,coalesce(sum(si.line_total),0) revenue,coalesce(sum((si.unit_price-si.cost_snapshot)*si.quantity),0) profit from sale_items si join sales s on s.id=si.sale_id and s.status='completed' join products p on p.id=si.product_id where (s.created_at at time zone 'Asia/Baku')::date between $1::date and $2::date group by p.id order by revenue desc limit 10`,[from,to]);
  const shifts=await sql.unsafe(`select u.full_name,cs.opened_at,cs.closed_at,cs.expected_cash,cs.actual_cash,case when cs.actual_cash is null then null else cs.actual_cash-cs.expected_cash end difference from cashier_shifts cs join users u on u.id=cs.cashier_id where (cs.opened_at at time zone 'Asia/Baku')::date between $1::date and $2::date order by cs.opened_at desc limit 12`,[from,to]);
  const movements=await sql.unsafe(`select sm.created_at,sm.type,p.name,sm.quantity,w.code as warehouse,wl.code as location_code from stock_movements sm join products p on p.id=sm.product_id join warehouses w on w.id=sm.warehouse_id left join warehouse_locations wl on wl.id=sm.location_id where (sm.created_at at time zone 'Asia/Baku')::date between $1::date and $2::date order by sm.created_at desc limit 15`,[from,to]);
  const employees=await sql.unsafe(`select u.full_name,u.role,count(ea.id) work_days,coalesce(sum(extract(epoch from (coalesce(ea.clock_out,now())-ea.clock_in))/3600),0) hours from users u left join employee_attendance ea on ea.user_id=u.id and (ea.clock_in at time zone 'Asia/Baku')::date between $1::date and $2::date where u.is_active=true group by u.id order by hours desc`,[from,to]);
  return NextResponse.json({range:{from,to},summary:{sales:Number(summary.sales),receipts:Number(summary.receipts),profit:Number(summary.profit),returns:Number(summary.returned_count)},daily:daily.map(r=>({day:r.report_date,total:Number(r.total),receipts:Number(r.receipts)})),products:products.map(r=>({...r,quantity:Number(r.quantity),revenue:Number(r.revenue),profit:Number(r.profit)})),shifts:shifts.map(r=>({...r,expected_cash:r.expected_cash==null?null:Number(r.expected_cash),actual_cash:r.actual_cash==null?null:Number(r.actual_cash),difference:r.difference==null?null:Number(r.difference)})),movements:movements.map(r=>({...r,location:r.location_code,quantity:Number(r.quantity)})),employees:employees.map(r=>({...r,work_days:Number(r.work_days),hours:Number(r.hours)}))});
}catch(error){console.error("reports.get",error);void logSystemError("reports.get", error);return NextResponse.json({error:"Hesabatlar yüklənmədi"},{status:500})}finally{await sql.end({timeout:2})}}
