import { NextResponse } from "next/server";
import { logSystemError } from "@/lib/log-error";
import postgres from "postgres";
import { salesWarehouseSql } from "@/lib/warehouse";

export const runtime="nodejs";
export const dynamic="force-dynamic";
const connection=()=>{if(!process.env.DATABASE_URL)throw new Error("DATABASE_URL təyin edilməyib");return postgres(process.env.DATABASE_URL,{max:1,prepare:false,connect_timeout:10})};

export async function GET(){const sql=connection();try{const rows=await sql.unsafe(`select so.id,so.order_no,so.status,so.total,so.note,so.created_at,so.customer_id,c.full_name customer_name,c.phone,coalesce(json_agg(json_build_object('productId',soi.product_id,'name',p.name,'quantity',soi.quantity,'unitPrice',soi.unit_price,'lineTotal',soi.line_total) order by soi.id) filter(where soi.id is not null),'[]'::json) items from sales_orders so join customers c on c.id=so.customer_id left join sales_order_items soi on soi.sales_order_id=so.id left join products p on p.id=soi.product_id group by so.id,c.full_name,c.phone order by so.created_at desc`);return NextResponse.json(rows.map(r=>({...r,total:Number(r.total),customerId:r.customer_id,items:r.items.map((i:any)=>({...i,quantity:Number(i.quantity),unitPrice:Number(i.unitPrice),lineTotal:Number(i.lineTotal)}))})));}catch(error){console.error("orders.get",error);void logSystemError("orders.get", error);return NextResponse.json({error:"Sifarişlər yüklənmədi"},{status:500})}finally{await sql.end({timeout:2})}}

export async function POST(request:Request){const sql=connection();try{const body=await request.json() as {action?:string;orderId?:string;status?:string;customerName?:string;phone?:string;productId?:string;quantity?:string|number;note?:string;items?:{productId?:string;quantity?:string|number}[]};const result=await sql.begin(async tx=>{const actorId=request.headers.get("x-birkassa-user-id");const [user]=await tx.unsafe("select id from users where id=$1 and is_active=true",[actorId]);if(!user)throw new Error("İstifadəçi tapılmadı");if(body.action==='status'){if(body.status==='completed')throw Object.assign(new Error("Təhvil yalnız kassada ödənişlə tamamlanır"),{statusCode:409});if(!body.orderId||!['ready','completed','cancelled'].includes(String(body.status)))throw Object.assign(new Error("Status əməliyyatı düzgün deyil"),{statusCode:400});const [order]=await tx.unsafe("select id,status from sales_orders where id=$1 for update",[body.orderId]);if(!order)throw Object.assign(new Error("Sifariş tapılmadı"),{statusCode:404});if(['completed','cancelled'].includes(order.status))throw Object.assign(new Error("Bağlanmış sifariş dəyişdirilə bilməz"),{statusCode:409});await tx.unsafe("update sales_orders set status=$1,updated_at=now() where id=$2",[body.status,order.id]);await tx.unsafe("insert into audit_logs (user_id,action,entity_type,entity_id,before_json,after_json) values ($1,'order.status_changed','sales_order',$2,$3,$4)",[user.id,order.id,JSON.stringify({status:order.status}),JSON.stringify({status:body.status})]);return{orderId:order.id,status:body.status}}
    const customerName=String(body.customerName||'').trim();const requested=(body.items?.length?body.items:[{productId:body.productId,quantity:body.quantity}]).map(item=>({productId:String(item.productId||""),quantity:Number(item.quantity)}));if(customerName.length<2||!requested.length||requested.some(item=>!item.productId||!Number.isFinite(item.quantity)||item.quantity<=0))throw Object.assign(new Error("Müştəri və məhsul sətirlərini düzgün yazın"),{statusCode:400});const lines=[];for(const item of requested){const [product]=await tx.unsafe(`select p.id,p.name,p.sale_price,coalesce(sum(sm.quantity),0) stock from products p left join stock_movements sm on sm.product_id=p.id and sm.warehouse_id=(select id from (${salesWarehouseSql(request.headers.get("x-birkassa-user-id") || "")}) sales_warehouse) where p.id=$1 and p.is_active=true group by p.id`,[item.productId]);if(!product)throw Object.assign(new Error("Məhsul tapılmadı"),{statusCode:404});if(item.quantity>Number(product.stock))throw Object.assign(new Error(`${product.name}: stok kifayət etmir. Qalıq: ${Number(product.stock)}`),{statusCode:409});const lineTotal=Number((item.quantity*Number(product.sale_price)).toFixed(2));lines.push({id:product.id,quantity:item.quantity,price:product.sale_price,lineTotal})}let [customer]=body.phone?await tx.unsafe("select id from customers where phone=$1 limit 1",[body.phone]):[];if(!customer)[customer]=await tx.unsafe("insert into customers (full_name,phone) values ($1,$2) returning id",[customerName,body.phone||null]);const [{next_no:nextNo}]=await tx.unsafe("select coalesce(max((regexp_replace(order_no,'[^0-9]','','g'))::bigint),0)+1 next_no from sales_orders");const orderNo=`S-${new Date().getFullYear()}-${String(nextNo).padStart(4,'0')}`,total=Number(lines.reduce((sum,line)=>sum+line.lineTotal,0).toFixed(2));const [order]=await tx.unsafe("insert into sales_orders (order_no,customer_id,total,note,created_by) values ($1,$2,$3,$4,$5) returning id,order_no",[orderNo,customer.id,total,body.note||null,user.id]);for(const line of lines)await tx.unsafe("insert into sales_order_items (sales_order_id,product_id,quantity,unit_price,line_total) values ($1,$2,$3,$4,$5)",[order.id,line.id,line.quantity,line.price,line.lineTotal]);await tx.unsafe("insert into audit_logs (user_id,action,entity_type,entity_id,after_json) values ($1,'order.created','sales_order',$2,$3)",[user.id,order.id,JSON.stringify({orderNo,total,customerName,itemCount:lines.length})]);return{orderId:order.id,orderNo,total,status:'pending'}});return NextResponse.json(result,{status:201})}catch(error:any){console.error("orders.post",error);void logSystemError("orders.post", error);return NextResponse.json({error:error?.message||"Sifariş əməliyyatı tamamlanmadı"},{status:error?.statusCode||500})}finally{await sql.end({timeout:2})}}
